fitness/dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"
urlpatterns = [
  path("", views.HomeView.as_view(), name="home"),
  path("weight_checkin/", views.WeightCheckInView.as_view(), name="weight_checkin"),
  path("weights_summary", views.WeightsView.as_view(), name="weights_summary"),
  path("weights/<int:pk>", views.WeightView.as_view(), name="weight"),
  path("weights/<int:pk>/delete", views.DestroyWeight.as_view(), name="weight_destroy")
]

fitness/fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("", RedirectView.as_view(url="/dashboard"), name="home"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("workouts/", include('workouts.urls')),
]

fitness/workouts/urls.py
from django.urls import path
from . import views


app_name = "workouts"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("new", views.CreateWorkoutView.as_view(), name="create_workout"),
    path("update/<int:pk>", views.UpdateWorkoutView.as_view(), name="update_workout"),
    path("delete/<int:pk>", views.DeleteWorkoutView.as_view(), name="delete_workout"),
    
]

fitness/workouts/models.py
from datetime import tzinfo
from django.db import models
from dashboard.models import Profile
from django.db.models.aggregates import Sum
from django.db.models.functions import TruncDay
from django.db.models import F
from base import FitnessModel
from django.utils import timezone
from django.db.models.functions import TruncDay
from simple_history.models import HistoricalRecords


class WorkoutManager(models.Manager):
    def chart_data(self):
        """Sum of intensity by workout date"""
        self.annotate(
            month=TruncDay("workout_datetime", tzinfo=timezone.tzinfo)
        ).values("month").annotate(total=Sum(F("duration") * F("effort")))


class Workout(FitnessModel):

    objects = WorkoutManager()
    history = HistoricalRecords()

    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="workouts"
    )
    name = models.CharField(max_length=255)
    workout_datetime = models.DateTimeField()
    duration = models.IntegerField(default=0)
    effort = models.IntegerField(default=5, choices=((x, str(x)) for x in range(1, 11)))
    description = models.TextField(blank=True)

    def pct(self):
        return int(round(100.0 * (self.effort / 10.0), 0))

    def intensity(self):
        return self.duration * self.effort

fitness/workouts/forms.py
from django import forms
from . import models

class WorkoutForm(forms.ModelForm):
    class Meta:
        model = models.Workout
        fields = ['name', 'workout_datetime', 'duration', 'effort', 'description']
        widgets = {
          'name': forms.TextInput(attrs={ 'autofocus': True }),
          'workout_datetime': forms.DateTimeInput(attrs={'data-controller': 'datepicker', 'data-datepicker-time': 'true' })
        }

fitness/workouts/views.py
from django.shortcuts import render, redirect
from dashboard.views import SecureView
from django.utils import timezone
from django.contrib.messages import add_message, SUCCESS

#
from . import forms



def workouts_for_me(user):
    return user.profile.workouts.order_by("-workout_datetime")


class HomeView(SecureView):
    def get(self, request):
        """render current users workouts"""
        workouts = workouts_for_me(request.user)
        chart = request.user.profile.workouts.chart_data

        #
        return render(
            request,
            "workouts/home.html",
            {
                "workouts": workouts,
                "chart": chart,
            },
        )


class CreateWorkoutView(SecureView):
    def get(self, request):
        form = forms.WorkoutForm(
            initial={"workout_datetime": timezone.now()}
        )
       
        return render(request, "workouts/new.html", {"form": form})

    def post(self, request):        
        form = forms.WorkoutForm(request.POST)
        form.instance.profile = request.user.profile
        if form.is_valid():
            form.save()
            add_message(request, SUCCESS, "Added workout successfully!")
            return redirect("workouts:home")
        return render(request, "workouts/new.html", {"form": form})


class UpdateWorkoutView(SecureView):
    def get(self, request, pk):
        workout = request.user.profile.workouts.get(pk=pk)
        form = forms.WorkoutForm(instance=workout)
        return render(request, "workouts/edit.html", {"form": form, "workout": workout})

    def post(self, request, pk):
        workout = request.user.profile.workouts.get(pk=pk)
        form = forms.WorkoutForm(request.POST, instance=workout)
        if form.is_valid():
            form.save()
            add_message(request, SUCCESS, "Updated workout successfully!")
            return redirect("workouts:home")
        return render(request, "workouts/edit.html", {"form": form})


class DeleteWorkoutView(SecureView):
    def get(self, request, pk):
        workout = request.user.profile.workouts.get(pk=pk)
        return render(request, "workouts/delete.html", {"workout": workout})

    def post(self, request, pk):
        request.user.profile.workouts.get(pk=pk).delete()
        return redirect("workouts:home")

fitness/workouts/templates/workouts/delete.html
{% extends 'layout.html' %}
{% load bootstrap5 %}
{% block body %}

  <h1>Remove the Workout Below?</h1>

  <form method="post">
    {% csrf_token %}
    <h3>Name: {{ workout.name }}</h3>
    <div class="border-top my-3 py-3">
    {% bootstrap_button 'Remove' button_class="btn-danger" %} 
    </div>
  </form>

{% endblock body %}

fitness/workouts/templates/workouts/edit.html
{% extends 'layout.html' %}
{% load bootstrap5 %}

{% block body %}
<div>
  <a href="{% url 'workouts:home' %}">Back to Workouts</a>
</div>

<div class="bg-light m-3 p-3 border rounded">
  <h1>Let's finish your workout!</h1>
  <form novalidate method="post" autocomplete="off">
    {% csrf_token %}
    {% bootstrap_field form.name %}
    {% bootstrap_field form.workout_datetime %}
    <div class="d-flex flex-wrap">
      {% bootstrap_field form.duration form_group_class="m-2"%}
      {% bootstrap_field form.effort form_group_class="m-2" %}
    </div>
    {% bootstrap_field form.description %}

    <div class="d-flex flex-wrap justify-content-between my-3">
      <div>
        {% bootstrap_button 'Update' %}
      </div>
      <div>
        <a href="{% url 'workouts:delete_workout' form.instance.id %}">Remove</a>
      </div>
    </div>
  </form>

  <div>
    <h3>History</h3>
    <div class="row m-2 bg-secondary text-white" style="font-size: .8em;">
      <div class="col">Name</div>
      
      <div class="col">duration</div>
      <div class="col">effort</div>
      <div class="col">history_date</div>
      <div class="col">User</div>
    </div>

    {% for h in workout.history.all %}
    <div class="row m-2" style="font-size: .8em;">
      
      <div class="col">
        <div >{{ h.name }}</div>
        {{ h.workout_datetime }}
      </div>
      <div class="col">{{ h.duration }}</div>
      <div class="col">{{ h.effort }}</div>
      <div class="col">{{ h.history_type }}{{ h.history_date }}</div>
      <div class="col">{{ h.history_user }}</div>
    </div>
    {% endfor %}

  </div>

</div>
{% endblock body %}

fitness/workouts/templates/workouts/home.html
{% extends 'layout.html' %}


{% block css %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% endblock css %}


{% block body %}
  <h4>Workouts</h4>

  <div class="menu-wrapper">
  <a href="{% url 'dashboard:home'%}">Back to Dashboard</a> | 
  <a href="{% url 'workouts:create_workout' %}">Create a new Workout</a>
  </div>

  
  <div class="border my-3 p-3  rounded">

  <h5>Workouts</h5>


  
  {% if workouts  %}
  <h5>Chart</h5>
  <div id="chart_div"></div>
 
  <div>
    <div class="row border-bottom bg-dark text-white">
    
        <div class="col-md-7">Name</div>        
        <div class="col-md-3">Duration(min)</div>
        <div class="col-md-2">Intensity</div>
 
    
      </div>
    {% for w in workouts %}
      <div class="row border-bottom py-2">
          <div class="col-md-7">
            <a href="{% url 'workouts:update_workout' w.id %}">{{ w.name }}</a>
            <div>{{ w.workout_datetime | date:"SHORT_DATETIME_FORMAT"}}</div>   
            <div class="progress">
              <div class="progress-bar bg-success" role="progressbar" style="width: {{w.pct}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                {{w.pct}}%  (effort {{w.effort}})

              </div>
            </div>       
          </div>
          
          <div class="col-md-3">{{ w.duration }}</div>
          <div class="col-md-2">{{ w.intensity }}</div> 

          
      </div>
    {% endfor %}
 
 
  {% else %}
    <h2 class="text-muted">Let's create a new workout today!</h2>
  {% endif %}
</div>



<script>

  google.charts.load('current', {packages: ['corechart', 'line']});
  google.charts.setOnLoadCallback(drawBasic);
  
  function drawBasic() {
  
        var data = new google.visualization.DataTable();
        data.addColumn('date', 'Date');
        data.addColumn('number', 'Intensity');
  
        data.addRows([           
            {% for w in chart %}
              [new Date({{w.month|date:"Y"}},{{w.month|date:"m"}},{{w.month|date:"d"}}), {{w.total}}],
            {% endfor %}            
        ]);
  
        var options = {
          hAxis: {
            title: 'Intensity'
          },
          vAxis: {
            title: 'Date'
          }
        };
  
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
  
        chart.draw(data, options);
      }
</script>
 




{% endblock body %}

fitness/workouts/templates/workouts/new.html
{% extends 'layout.html' %}
{% load bootstrap5 %}

{% block body %}
<div>
  <a href="{% url 'workouts:home' %}">Back to Workouts</a>
</div>

<div class="bg-light m-3 p-3 border rounded">
  <h1>Tell us about your workout!</h1>
  <form novalidate method="post" autocomplete="off">
      {% csrf_token %}
      {% bootstrap_field form.name %}
      {% bootstrap_field form.workout_datetime %}
      <div class="d-flex flex-wrap">
      {% bootstrap_field form.duration form_group_class="m-2"%}
      {% bootstrap_field form.effort form_group_class="m-2" %}      
      </div>
      {% bootstrap_field form.description %}

      <div class="my-3">
      {% bootstrap_button 'Create' %}
      </div>
  </form>
</div>  
{% endblock body %}