fitness/dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"
urlpatterns = [
  path("", views.HomeView.as_view(), name="home"),
  path("weight_checkin/", views.WeightCheckInView.as_view(), name="weight_checkin"),
  path("weights_summary", views.WeightsView.as_view(), name="weights_summary"),
  path("weights/<int:pk>", views.WeightView.as_view(), name="weight"),
  path("weights/<int:pk>/delete", views.DestroyWeight.as_view(), name="weight_destroy")
]

fitness/fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("dashboard/", include("dashboard.urls")),
    path("", RedirectView.as_view(url="/dashboard"), name="home"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("workouts/", include('workouts.urls')),
]

fitness/dashboard/models.py
from django.db import models
from django.db.models.query_utils import Q
from django.contrib.auth.models import User
from django.forms import ValidationError
from base import FitnessModel
from django.db.models import Deferrable


class Profile(FitnessModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)


class Weight(FitnessModel):
    lbs = models.DecimalField(decimal_places=2, max_digits=5)
    entry_date = models.DateTimeField(null=True)
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="weights"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["entry_date", "profile"],
                name="unique_weight_by_day_for_user_profile",
            )
            
        ]

    def clean(self):
        self.validate_unique()
        
        
  

fitness/dashboard/forms.py
from django.forms import ModelForm
from . import models
from django import forms

 

class WeightForm(ModelForm):
  class Meta:
      model = models.Weight
      fields = ['lbs', 'entry_date']
      widgets = {
        'entry_date': forms.DateInput(attrs={'data-controller': 'datepicker'}),
        'lbs': forms.TextInput(attrs={'autofocus':True})
      }

fitness/dashboard/views.py
from django.shortcuts import redirect, render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import WeightForm
from django.contrib import messages
from django.contrib.messages import SUCCESS
from .models import Weight
from django.shortcuts import get_object_or_404
from django.utils import timezone


class SecureView(LoginRequiredMixin, View):
    """Inherit views from this"""

    pass


class HomeView(SecureView):
    def get(self, request):
        return render(request, "dashboard/home.html")


class WeightCheckInView(SecureView):
    """Handles the Weight Creation"""

    def get(self, request):
        """New Entry for Weight for day"""
        form = WeightForm(initial={"entry_date": timezone.now().date()})
        context = {"form": form}
        return render(request, "dashboard/checkin/new.html", context)

    def post(self, request):
        """Create new Weight entry for day"""
        weight = Weight(profile=request.user.profile)
        #
        form = WeightForm(request.POST, instance=weight)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Thanks for your weight!")
            return redirect("dashboard:home")
        context = {"form": form}
        return render(request, "dashboard/checkin/new.html", context)


class WeightsView(SecureView):
    """Dashboard partial"""

    def get(self, request):
        """Display Weights in dashboard partial"""
        weights = Weight.objects.order_by("-entry_date").all()
        chart = [[x.entry_date, x.lbs] for x in weights]

        context = {"weights": weights, "chart": chart}
        return render(request, "dashboard/weights/_summary.html", context)


class WeightView(SecureView):
    def get(self, request, pk):
        """Display a selected Weight"""
        weight = get_object_or_404(Weight, pk=pk)
        context = {"weight": weight}
        return render(request, "dashboard/weights/show.html", context)


class DestroyWeight(SecureView):
    def post(self, request, pk):
        """Destroy the selected Weight"""
        get_object_or_404(Weight, pk=pk).delete()
        messages.add_message(request, SUCCESS, "Removed Weight successfully!")
        return redirect("dashboard:home")

fitness/dashboard/templates/dashboard/weights/_summary.html
<h1>This Week</h1>


<table class="table">
  <thead>
      <tr>
        <th>Lbs</th>
        <th>Date</th>
      </tr>
  </thead>
  {% for weight in weights %}
  <tr>
    <td>{{ weight.lbs }}</td>
    <td><a href="{% url 'dashboard:weight' weight.id %}">{{ weight.entry_date |date }}</a></td>
  </tr>
  {% endfor %}

</table>




<script>

  google.charts.load('current', {packages: ['corechart', 'line']});
  google.charts.setOnLoadCallback(drawBasic);
  
  function drawBasic() {
  
        var data = new google.visualization.DataTable();
        data.addColumn('date', 'Date');
        data.addColumn('number', 'Weight');
  
        data.addRows([           
            {% for x,y in chart %}              
              [new Date({{x|date:"Y"}},{{x|date:"m"}},{{x|date:"d"}}), {{y}}],
            {% endfor %}            
        ]);
  
        var options = {
          hAxis: {
            title: 'Time'
          },
          vAxis: {
            title: 'Weight'
          }
        };
  
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
  
        chart.draw(data, options);
      }
</script>
 

fitness/dashboard/templates/dashboard/weights/show.html
{% extends 'layout.html' %}
{% load bootstrap5 %}

{% block body %}
  <div class="border-bottom py-3 my-2">
    <a href="{% url 'dashboard:home' %}">Back to Dashboard</a>
  </div>

  <h1>Your Weight</h1>
  
  <dl>
    <dt>Lbs</dt>
    <dd>{{ weight.lbs }}</dd>
    <dt>Entry Date</dt>
    <dd>{{ weight.entry_date | date }}</dd>
  </dl>

  <form method="post" action="{% url 'dashboard:weight_destroy' weight.id %}" >
    {% csrf_token %}
    {% bootstrap_button 'Destroy Weight' %}
  </form>

{% endblock body %}